# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geoutil_coreg.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeoUtilsCoReg(object):
    def setupUi(self, GeoUtilsCoReg):
        GeoUtilsCoReg.setObjectName("GeoUtilsCoReg")
        GeoUtilsCoReg.resize(513, 482)
        GeoUtilsCoReg.setMinimumSize(QtCore.QSize(513, 482))
        GeoUtilsCoReg.setMaximumSize(QtCore.QSize(513, 550))
        self.formLayout = QtWidgets.QFormLayout(GeoUtilsCoReg)
        self.formLayout.setObjectName("formLayout")
        self.actionLoadPrimary = QtWidgets.QPushButton(GeoUtilsCoReg)
        self.actionLoadPrimary.setObjectName("actionLoadPrimary")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.actionLoadPrimary)
        self.lineEdit = QtWidgets.QLineEdit(GeoUtilsCoReg)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.actionLoadSecondary = QtWidgets.QPushButton(GeoUtilsCoReg)
        self.actionLoadSecondary.setObjectName("actionLoadSecondary")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.actionLoadSecondary)
        self.lineEdit_2 = QtWidgets.QLineEdit(GeoUtilsCoReg)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.line = QtWidgets.QFrame(GeoUtilsCoReg)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.label = QtWidgets.QLabel(GeoUtilsCoReg)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_2.setStatusTip("")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textIterations = QtWidgets.QSpinBox(GeoUtilsCoReg)
        self.textIterations.setProperty("value", 5)
        self.textIterations.setObjectName("textIterations")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.textIterations)
        self.label_12 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textMask = QtWidgets.QLineEdit(GeoUtilsCoReg)
        self.textMask.setReadOnly(True)
        self.textMask.setObjectName("textMask")
        self.horizontalLayout.addWidget(self.textMask)
        self.actionLoadMask = QtWidgets.QToolButton(GeoUtilsCoReg)
        self.actionLoadMask.setObjectName("actionLoadMask")
        self.horizontalLayout.addWidget(self.actionLoadMask)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_13 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textShapefileMask = QtWidgets.QLineEdit(GeoUtilsCoReg)
        self.textShapefileMask.setObjectName("textShapefileMask")
        self.horizontalLayout_2.addWidget(self.textShapefileMask)
        self.actionLoadShapefile = QtWidgets.QToolButton(GeoUtilsCoReg)
        self.actionLoadShapefile.setObjectName("actionLoadShapefile")
        self.horizontalLayout_2.addWidget(self.actionLoadShapefile)
        self.formLayout.setLayout(12, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.textNoDataValue = QtWidgets.QLineEdit(GeoUtilsCoReg)
        self.textNoDataValue.setObjectName("textNoDataValue")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.textNoDataValue)
        self.label_4 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.textMinimumPointCount = QtWidgets.QLineEdit(GeoUtilsCoReg)
        self.textMinimumPointCount.setObjectName("textMinimumPointCount")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.textMinimumPointCount)
        self.label_5 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.textMaximumHeightFilter = QtWidgets.QLineEdit(GeoUtilsCoReg)
        self.textMaximumHeightFilter.setObjectName("textMaximumHeightFilter")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.textMaximumHeightFilter)
        self.label_6 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.textMinimumHeightFilter = QtWidgets.QLineEdit(GeoUtilsCoReg)
        self.textMinimumHeightFilter.setObjectName("textMinimumHeightFilter")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.textMinimumHeightFilter)
        self.label_7 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.textMaximumResidualAllowance = QtWidgets.QLineEdit(GeoUtilsCoReg)
        self.textMaximumResidualAllowance.setObjectName("textMaximumResidualAllowance")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.textMaximumResidualAllowance)
        self.label_8 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.textPolynomialDegree = QtWidgets.QLineEdit(GeoUtilsCoReg)
        self.textPolynomialDegree.setObjectName("textPolynomialDegree")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.textPolynomialDegree)
        self.label_9 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboExtractionGrid = QtWidgets.QComboBox(GeoUtilsCoReg)
        self.comboExtractionGrid.setObjectName("comboExtractionGrid")
        self.comboExtractionGrid.addItem("")
        self.comboExtractionGrid.addItem("")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.comboExtractionGrid)
        self.label_10 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboSaveStats = QtWidgets.QComboBox(GeoUtilsCoReg)
        self.comboSaveStats.setObjectName("comboSaveStats")
        self.comboSaveStats.addItem("")
        self.comboSaveStats.addItem("")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.comboSaveStats)
        self.label_11 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboICESATDEM = QtWidgets.QComboBox(GeoUtilsCoReg)
        self.comboICESATDEM.setObjectName("comboICESATDEM")
        self.comboICESATDEM.addItem("")
        self.comboICESATDEM.addItem("")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.comboICESATDEM)
        self.line_2 = QtWidgets.QFrame(GeoUtilsCoReg)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.actionRun = QtWidgets.QPushButton(GeoUtilsCoReg)
        self.actionRun.setObjectName("actionRun")
        self.formLayout.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.actionRun)
        self.label_15 = QtWidgets.QLabel(GeoUtilsCoReg)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.comboVerticalShift = QtWidgets.QComboBox(GeoUtilsCoReg)
        self.comboVerticalShift.setObjectName("comboVerticalShift")
        self.comboVerticalShift.addItem("")
        self.comboVerticalShift.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboVerticalShift)
        self.progressBar = QtWidgets.QProgressBar(GeoUtilsCoReg)
        self.progressBar.setMaximum(12)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(25, QtWidgets.QFormLayout.FieldRole, self.progressBar)
        self.log = QtWidgets.QLabel(GeoUtilsCoReg)
        self.log.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.log.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.log.setObjectName("log")
        self.formLayout.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.log)
        self.actionAbout = QtWidgets.QPushButton(GeoUtilsCoReg)
        self.actionAbout.setObjectName("actionAbout")
        self.formLayout.setWidget(25, QtWidgets.QFormLayout.LabelRole, self.actionAbout)

        self.retranslateUi(GeoUtilsCoReg)
        self.comboICESATDEM.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GeoUtilsCoReg)

    def retranslateUi(self, GeoUtilsCoReg):
        _translate = QtCore.QCoreApplication.translate
        GeoUtilsCoReg.setWindowTitle(_translate("GeoUtilsCoReg", "GeoUtils Co-Registration"))
        self.actionLoadPrimary.setText(_translate("GeoUtilsCoReg", "Load Primary"))
        self.actionLoadSecondary.setText(_translate("GeoUtilsCoReg", "Load Secondary"))
        self.label.setText(_translate("GeoUtilsCoReg", "Optional Arguements"))
        self.label_2.setText(_translate("GeoUtilsCoReg", "Iterations"))
        self.textIterations.setToolTip(_translate("GeoUtilsCoReg", "number of iterations"))
        self.label_12.setText(_translate("GeoUtilsCoReg", "Mask"))
        self.textMask.setToolTip(_translate("GeoUtilsCoReg", "path to a mask of same size as the master DEM, to filter out non stable areas such as glaciers. Points with mask>0 are masked."))
        self.actionLoadMask.setText(_translate("GeoUtilsCoReg", "..."))
        self.label_13.setText(_translate("GeoUtilsCoReg", "Shapefile Mask"))
        self.textShapefileMask.setToolTip(_translate("GeoUtilsCoReg", "path to a shapefile containing outlines of objects to mask, such as RGI shapefiles"))
        self.actionLoadShapefile.setText(_translate("GeoUtilsCoReg", "..."))
        self.label_3.setText(_translate("GeoUtilsCoReg", "No Data Value"))
        self.textNoDataValue.setText(_translate("GeoUtilsCoReg", "none"))
        self.label_4.setText(_translate("GeoUtilsCoReg", "Minimum Point Count"))
        self.textMinimumPointCount.setToolTip(_translate("GeoUtilsCoReg", "minimum number of points in each aspect bin to be considered valid"))
        self.textMinimumPointCount.setText(_translate("GeoUtilsCoReg", "30"))
        self.label_5.setText(_translate("GeoUtilsCoReg", "Maximum Height Filter"))
        self.textMaximumHeightFilter.setToolTip(_translate("GeoUtilsCoReg", "points with altitude above zmax are masked during the vertical alignment, e.g snow covered areas"))
        self.textMaximumHeightFilter.setText(_translate("GeoUtilsCoReg", "none"))
        self.label_6.setText(_translate("GeoUtilsCoReg", "Minimum Height Filter"))
        self.textMinimumHeightFilter.setToolTip(_translate("GeoUtilsCoReg", "points with altitude below zmin are masked during the vertical alignment, e.g points on sea"))
        self.textMinimumHeightFilter.setText(_translate("GeoUtilsCoReg", "none"))
        self.label_7.setText(_translate("GeoUtilsCoReg", "Maximum Residual Allowance"))
        self.textMaximumResidualAllowance.setToolTip(_translate("GeoUtilsCoReg", "maximum value of the residuals, points where |dh|>resmax are considered as outliers and removed"))
        self.textMaximumResidualAllowance.setText(_translate("GeoUtilsCoReg", "none"))
        self.label_8.setText(_translate("GeoUtilsCoReg", "Polynomial Degree (Res Fitting)"))
        self.textPolynomialDegree.setToolTip(_translate("GeoUtilsCoReg", "egree of the polynomial to be fit to residuals and removed. Set to <0 to disable."))
        self.textPolynomialDegree.setText(_translate("GeoUtilsCoReg", "1"))
        self.label_9.setText(_translate("GeoUtilsCoReg", "Extraction Grid"))
        self.comboExtractionGrid.setToolTip(_translate("GeoUtilsCoReg", "master\' or \'slave\' : only the intersection of both DEMs is extracted, either in the grid of the master DEM, or the slave (default is master DEM grid)."))
        self.comboExtractionGrid.setItemText(0, _translate("GeoUtilsCoReg", "Primary"))
        self.comboExtractionGrid.setItemText(1, _translate("GeoUtilsCoReg", "Secondary"))
        self.label_10.setText(_translate("GeoUtilsCoReg", "Save Stats"))
        self.comboSaveStats.setToolTip(_translate("GeoUtilsCoReg", "Save horizontal and median vertical offset in a text file"))
        self.comboSaveStats.setItemText(0, _translate("GeoUtilsCoReg", "Yes"))
        self.comboSaveStats.setItemText(1, _translate("GeoUtilsCoReg", "No"))
        self.label_11.setText(_translate("GeoUtilsCoReg", "ICESAT DEM"))
        self.comboICESATDEM.setToolTip(_translate("GeoUtilsCoReg", "Master DEM are IceSAT data instead of a raster DEM. master_dem must then be a string to the file name or regular expression to several files (use quotes)"))
        self.comboICESATDEM.setCurrentText(_translate("GeoUtilsCoReg", "No"))
        self.comboICESATDEM.setItemText(0, _translate("GeoUtilsCoReg", "No"))
        self.comboICESATDEM.setItemText(1, _translate("GeoUtilsCoReg", "Yes"))
        self.actionRun.setText(_translate("GeoUtilsCoReg", "Run"))
        self.label_15.setText(_translate("GeoUtilsCoReg", "Vertical Shift"))
        self.comboVerticalShift.setItemText(0, _translate("GeoUtilsCoReg", "True"))
        self.comboVerticalShift.setItemText(1, _translate("GeoUtilsCoReg", "False"))
        self.log.setText(_translate("GeoUtilsCoReg", "GeoUtils Coregistration"))
        self.actionAbout.setText(_translate("GeoUtilsCoReg", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GeoUtilsCoReg = QtWidgets.QDialog()
    ui = Ui_GeoUtilsCoReg()
    ui.setupUi(GeoUtilsCoReg)
    GeoUtilsCoReg.show()
    sys.exit(app.exec_())
